"""
sql/validator.py

Safety validator for SQL generated by an LLM (or anywhere else untrusted).

Three layers of defense:
  1. Parse with sqlglot. Reject anything that isn't valid SQL.
  2. Statement-type check. Reject anything that isn't a SELECT.
  3. Table allow-list. Reject any reference to a table outside our schema.

Optionally enforces a row limit by injecting LIMIT N into queries that don't
have one.
"""

from __future__ import annotations

from dataclasses import dataclass

import sqlglot
from sqlglot import exp
from sqlglot.errors import ParseError


# Tables the LLM is allowed to query.
DEFAULT_ALLOWED_TABLES: frozenset[str] = frozenset(
    {
        "customers",
        "products",
        "orders",
        "order_items",
    }
)


class SQLValidationError(Exception):
    """Raised when a SQL statement fails any validation layer."""


@dataclass(frozen=True, slots=True)
class ValidationResult:
    """Outcome of validating a SQL statement."""

    sql: str
    tables_referenced: tuple[str, ...]
    row_limit_added: bool


class SQLValidator:
    """Validates LLM-generated SQL against an allow-list of tables and statement types."""

    def __init__(
        self,
        *,
        allowed_tables: frozenset[str] = DEFAULT_ALLOWED_TABLES,
        default_row_limit: int | None = 1000,
        dialect: str = "duckdb",
    ) -> None:
        self._allowed_tables = frozenset(t.lower() for t in allowed_tables)
        self._default_row_limit = default_row_limit
        self._dialect = dialect

    def validate(self, sql: str) -> ValidationResult:
        """Validate `sql`, returning the (possibly rewritten) safe SQL."""
        if not sql or not sql.strip():
            raise SQLValidationError("Empty SQL.")

        # Layer 1: parse
        try:
            parsed = sqlglot.parse_one(sql, read=self._dialect)
        except ParseError as exc:
            raise SQLValidationError(f"Failed to parse SQL: {exc}") from exc

        if parsed is None:
            raise SQLValidationError("SQL did not parse to a recognizable statement.")

        # Layer 2: statement type
        if not isinstance(parsed, exp.Select):
            statement_name = type(parsed).__name__.upper()
            raise SQLValidationError(f"Only SELECT statements are allowed; got {statement_name}.")

        # Reject any mutating subordinate statements
        for node in parsed.walk():
            if isinstance(
                node,
                (
                    exp.Insert,
                    exp.Update,
                    exp.Delete,
                    exp.Drop,
                    exp.Create,
                    exp.Alter,
                    exp.TruncateTable,
                ),
            ):
                raise SQLValidationError(f"Mutation operation not allowed: {type(node).__name__}.")

        # Layer 3: table allow-list
        # Collect CTE alias names first -- they are virtual tables, not real ones.
        cte_names: set[str] = set()
        for cte in parsed.find_all(exp.CTE):
            alias = cte.alias_or_name
            if alias:
                cte_names.add(alias.lower())

        tables_referenced: set[str] = set()
        for table_node in parsed.find_all(exp.Table):
            table_name = table_node.name.lower()
            if table_name in cte_names:
                continue
            tables_referenced.add(table_name)
            if table_name not in self._allowed_tables:
                raise SQLValidationError(
                    f"Reference to disallowed table: '{table_name}'. "
                    f"Allowed tables: {sorted(self._allowed_tables)}."
                )

        if not tables_referenced:
            raise SQLValidationError("Query does not reference any table.")

        # Optional: ensure a row limit exists
        row_limit_added = False
        if self._default_row_limit is not None and parsed.args.get("limit") is None:
            parsed.set("limit", exp.Limit(expression=exp.Literal.number(self._default_row_limit)))
            row_limit_added = True

        return ValidationResult(
            sql=parsed.sql(dialect=self._dialect),
            tables_referenced=tuple(sorted(tables_referenced)),
            row_limit_added=row_limit_added,
        )
